spring:
  datasourse:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  liquibase:
    change-log: changelog/db.changelog-master.xml
    enabled: false
  jpa:
    show-sql: true
    activemq:
      in-memory: true
      pool.enabled: false
      trust-all: true
